export interface GameData {
  id: string;
  name: string;
  nameKh: string;
  slug: string;
  bannerUrl: string;
  iconUrl: string;
  publisher: string;
  hasZoneId: boolean;
  zoneIdPlaceholder: string;
  userIdPlaceholder: string;
  guideImage?: string;
  guideTextKh: string;
  guideTextEn: string;
  isActive: boolean;
  sortOrder: number;
  packages: PackageData[];
}

export interface PackageData {
  id: string;
  gameId: string;
  name: string;
  diamondsCount: number;
  bonusDiamonds: number;
  moogoldProductId: string;
  moogoldVariationId: string;
  originalPriceUSD: number;
  sellingPriceUSD: number;
  sellingPriceKHR: number;
  isAvailable: boolean;
  badgeText?: string;
  sortOrder: number;
}

export const INITIAL_GAMES: GameData[] = [
  {
    id: "game-mlbb",
    name: "Mobile Legends: Bang Bang",
    nameKh: "ម៉ូបាលឡេជែន (MLBB)",
    slug: "mobile-legends",
    bannerUrl: "/images/games/mlbb-banner.jpg",
    iconUrl: "/images/games/mlbb-icon.jpg",
    publisher: "Moonton",
    hasZoneId: true,
    zoneIdPlaceholder: "Zone ID (ឧទាហរណ៍ 2024)",
    userIdPlaceholder: "User ID (ឧទាហរណ៍ 12345678)",
    guideTextKh: "ដើម្បីស្វែងរក User ID និង Zone ID សូមចុចលើរូបតំណាង Profile នៅជ្រុងខាងឆ្វេងផ្នែកខាងលើក្នុងហ្គេម។ ID នឹងបង្ហាញជាទម្រង់ 12345678 (2024)។",
    guideTextEn: "To find your User ID and Zone ID, tap your profile avatar in the top-left corner of the game. Your ID appears in the format 12345678 (2024).",
    isActive: true,
    sortOrder: 1,
    packages: [
      {
        id: "pkg-mlbb-weekly",
        gameId: "game-mlbb",
        name: "Weekly Diamond Pass",
        diamondsCount: 220,
        bonusDiamonds: 0,
        moogoldProductId: "13",
        moogoldVariationId: "1001",
        originalPriceUSD: 2.30,
        sellingPriceUSD: 1.99,
        sellingPriceKHR: 8150,
        isAvailable: true,
        badgeText: "🔥 លក់ដាច់បំផុត (BESTSELLER)",
        sortOrder: 1,
      },
      {
        id: "pkg-mlbb-86",
        gameId: "game-mlbb",
        name: "86 Diamonds",
        diamondsCount: 78,
        bonusDiamonds: 8,
        moogoldProductId: "13",
        moogoldVariationId: "1002",
        originalPriceUSD: 1.50,
        sellingPriceUSD: 1.35,
        sellingPriceKHR: 5500,
        isAvailable: true,
        badgeText: "+8 Bonus",
        sortOrder: 2,
      },
      {
        id: "pkg-mlbb-172",
        gameId: "game-mlbb",
        name: "172 Diamonds",
        diamondsCount: 156,
        bonusDiamonds: 16,
        moogoldProductId: "13",
        moogoldVariationId: "1003",
        originalPriceUSD: 3.00,
        sellingPriceUSD: 2.70,
        sellingPriceKHR: 11000,
        isAvailable: true,
        badgeText: "+16 Bonus",
        sortOrder: 3,
      },
      {
        id: "pkg-mlbb-257",
        gameId: "game-mlbb",
        name: "257 Diamonds",
        diamondsCount: 234,
        bonusDiamonds: 23,
        moogoldProductId: "13",
        moogoldVariationId: "1004",
        originalPriceUSD: 4.40,
        sellingPriceUSD: 3.95,
        sellingPriceKHR: 16200,
        isAvailable: true,
        badgeText: "+23 Bonus",
        sortOrder: 4,
      },
      {
        id: "pkg-mlbb-706",
        gameId: "game-mlbb",
        name: "706 Diamonds",
        diamondsCount: 625,
        bonusDiamonds: 81,
        moogoldProductId: "13",
        moogoldVariationId: "1005",
        originalPriceUSD: 11.50,
        sellingPriceUSD: 10.50,
        sellingPriceKHR: 43000,
        isAvailable: true,
        badgeText: "⭐ ពេញនិយម (POPULAR)",
        sortOrder: 5,
      },
      {
        id: "pkg-mlbb-2195",
        gameId: "game-mlbb",
        name: "2,195 Diamonds",
        diamondsCount: 1860,
        bonusDiamonds: 335,
        moogoldProductId: "13",
        moogoldVariationId: "1006",
        originalPriceUSD: 35.00,
        sellingPriceUSD: 32.00,
        sellingPriceKHR: 131200,
        isAvailable: true,
        badgeText: "💎 VIP VALUE",
        sortOrder: 6,
      },
    ],
  },
  {
    id: "game-freefire",
    name: "Free Fire",
    nameKh: "ហ្វ្រីហ្វាយ (Free Fire)",
    slug: "free-fire",
    bannerUrl: "/images/games/freefire-banner.jpg",
    iconUrl: "/images/games/freefire-icon.jpg",
    publisher: "Garena",
    hasZoneId: false,
    zoneIdPlaceholder: "",
    userIdPlaceholder: "Player ID (ឧទាហរណ៍ 892341829)",
    guideTextKh: "ចូលទៅកាន់ប្រូហ្វាល់ហ្គេមរបស់អ្នកនៅជ្រុងឆ្វេងខាងលើ UID នឹងមានលេខប្រមាណ 9-10 ខ្ទង់។",
    guideTextEn: "Go to your in-game profile at the top left corner. Your Player ID is a 9-10 digit number.",
    isActive: true,
    sortOrder: 2,
    packages: [
      {
        id: "pkg-ff-100",
        gameId: "game-freefire",
        name: "100 Diamonds",
        diamondsCount: 100,
        bonusDiamonds: 0,
        moogoldProductId: "12",
        moogoldVariationId: "2001",
        originalPriceUSD: 1.10,
        sellingPriceUSD: 0.95,
        sellingPriceKHR: 3900,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "pkg-ff-310",
        gameId: "game-freefire",
        name: "310 Diamonds",
        diamondsCount: 310,
        bonusDiamonds: 31,
        moogoldProductId: "12",
        moogoldVariationId: "2002",
        originalPriceUSD: 3.10,
        sellingPriceUSD: 2.80,
        sellingPriceKHR: 11500,
        isAvailable: true,
        badgeText: "+31 Bonus",
        sortOrder: 2,
      },
      {
        id: "pkg-ff-520",
        gameId: "game-freefire",
        name: "520 Diamonds",
        diamondsCount: 520,
        bonusDiamonds: 52,
        moogoldProductId: "12",
        moogoldVariationId: "2003",
        originalPriceUSD: 5.00,
        sellingPriceUSD: 4.50,
        sellingPriceKHR: 18500,
        isAvailable: true,
        badgeText: "🔥 ពេញនិយម",
        sortOrder: 3,
      },
      {
        id: "pkg-ff-1060",
        gameId: "game-freefire",
        name: "1,060 Diamonds",
        diamondsCount: 1060,
        bonusDiamonds: 106,
        moogoldProductId: "12",
        moogoldVariationId: "2004",
        originalPriceUSD: 9.90,
        sellingPriceUSD: 8.90,
        sellingPriceKHR: 36500,
        isAvailable: true,
        badgeText: "💎 VIP VALUE",
        sortOrder: 4,
      },
    ],
  },
  {
    id: "game-pubg",
    name: "PUBG Mobile",
    nameKh: "ផាប់ជីម៉ូបាល (PUBG Mobile)",
    slug: "pubg-mobile",
    bannerUrl: "/images/games/pubg-banner.jpg",
    iconUrl: "/images/games/pubg-icon.jpg",
    publisher: "Level Infinite",
    hasZoneId: false,
    zoneIdPlaceholder: "",
    userIdPlaceholder: "Character ID (ឧទាហរណ៍ 512399238)",
    guideTextKh: "ចូលក្នុង Menu Profile របស់អ្នកក្នុង PUBG Mobile រួចកូពី Character ID (លេខ 10 ខ្ទង់)។",
    guideTextEn: "Open your PUBG Mobile profile menu and copy your 10-digit Character ID.",
    isActive: true,
    sortOrder: 3,
    packages: [
      {
        id: "pkg-pubg-60",
        gameId: "game-pubg",
        name: "60 UC",
        diamondsCount: 60,
        bonusDiamonds: 0,
        moogoldProductId: "11",
        moogoldVariationId: "3001",
        originalPriceUSD: 1.10,
        sellingPriceUSD: 0.99,
        sellingPriceKHR: 4100,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "pkg-pubg-325",
        gameId: "game-pubg",
        name: "325 UC (300+25)",
        diamondsCount: 300,
        bonusDiamonds: 25,
        moogoldProductId: "11",
        moogoldVariationId: "3002",
        originalPriceUSD: 5.20,
        sellingPriceUSD: 4.80,
        sellingPriceKHR: 19700,
        isAvailable: true,
        badgeText: "+25 Free UC",
        sortOrder: 2,
      },
      {
        id: "pkg-pubg-660",
        gameId: "game-pubg",
        name: "660 UC (600+60)",
        diamondsCount: 600,
        bonusDiamonds: 60,
        moogoldProductId: "11",
        moogoldVariationId: "3003",
        originalPriceUSD: 10.50,
        sellingPriceUSD: 9.50,
        sellingPriceKHR: 39000,
        isAvailable: true,
        badgeText: "⭐ Royale Pass",
        sortOrder: 3,
      },
      {
        id: "pkg-pubg-1800",
        gameId: "game-pubg",
        name: "1,800 UC (1500+300)",
        diamondsCount: 1500,
        bonusDiamonds: 300,
        moogoldProductId: "11",
        moogoldVariationId: "3004",
        originalPriceUSD: 26.00,
        sellingPriceUSD: 24.00,
        sellingPriceKHR: 98400,
        isAvailable: true,
        badgeText: "🔥 Best Value",
        sortOrder: 4,
      },
    ],
  },
  {
    id: "game-hok",
    name: "Honor of Kings",
    nameKh: "អន័រអហ្វឃីង (Honor of Kings)",
    slug: "honor-of-kings",
    bannerUrl: "/images/games/hok-banner.jpg",
    iconUrl: "/images/games/hok-icon.jpg",
    publisher: "Level Infinite",
    hasZoneId: false,
    zoneIdPlaceholder: "",
    userIdPlaceholder: "Player UID (ឧទាហរណ៍ 782341991)",
    guideTextKh: "ចុចលើ Profile Picture ក្នុងហ្គេមដើម្បីមើល UID របស់អ្នក។",
    guideTextEn: "Tap your in-game avatar to see and copy your Player UID.",
    isActive: true,
    sortOrder: 4,
    packages: [
      {
        id: "pkg-hok-80",
        gameId: "game-hok",
        name: "80 Tokens",
        diamondsCount: 80,
        bonusDiamonds: 0,
        moogoldProductId: "15",
        moogoldVariationId: "4001",
        originalPriceUSD: 1.10,
        sellingPriceUSD: 0.95,
        sellingPriceKHR: 3900,
        isAvailable: true,
        sortOrder: 1,
      },
      {
        id: "pkg-hok-257",
        gameId: "game-hok",
        name: "240+17 Tokens",
        diamondsCount: 240,
        bonusDiamonds: 17,
        moogoldProductId: "15",
        moogoldVariationId: "4002",
        originalPriceUSD: 3.10,
        sellingPriceUSD: 2.85,
        sellingPriceKHR: 11700,
        isAvailable: true,
        badgeText: "+17 Bonus",
        sortOrder: 2,
      },
      {
        id: "pkg-hok-895",
        gameId: "game-hok",
        name: "800+95 Tokens",
        diamondsCount: 800,
        bonusDiamonds: 95,
        moogoldProductId: "15",
        moogoldVariationId: "4003",
        originalPriceUSD: 10.20,
        sellingPriceUSD: 9.20,
        sellingPriceKHR: 37700,
        isAvailable: true,
        badgeText: "⭐ ពេញនិយម",
        sortOrder: 3,
      },
    ],
  },
  {
    id: "game-genshin",
    name: "Genshin Impact",
    nameKh: "ហ្គេនស៊ីនអ៊ីមផេក (Genshin)",
    slug: "genshin-impact",
    bannerUrl: "/images/games/genshin-banner.jpg",
    iconUrl: "/images/games/genshin-icon.jpg",
    publisher: "HoYoverse",
    hasZoneId: true,
    zoneIdPlaceholder: "Server (Asia / America / Europe)",
    userIdPlaceholder: "UID (ឧទាហរណ៍ 812345678)",
    guideTextKh: "UID របស់អ្នកបង្ហាញនៅជ្រុងខាងស្តាំក្រោមនៃអេក្រង់ហ្គេមជានិច្ច។",
    guideTextEn: "Your UID is displayed in the bottom-right corner of your screen at all times.",
    isActive: true,
    sortOrder: 5,
    packages: [
      {
        id: "pkg-genshin-welkin",
        gameId: "game-genshin",
        name: "Blessing of the Welkin Moon",
        diamondsCount: 3000,
        bonusDiamonds: 0,
        moogoldProductId: "14",
        moogoldVariationId: "5001",
        originalPriceUSD: 5.50,
        sellingPriceUSD: 4.90,
        sellingPriceKHR: 20000,
        isAvailable: true,
        badgeText: "🌙 លក់ដាច់បំផុត",
        sortOrder: 1,
      },
      {
        id: "pkg-genshin-330",
        gameId: "game-genshin",
        name: "300 + 30 Genesis Crystals",
        diamondsCount: 300,
        bonusDiamonds: 30,
        moogoldProductId: "14",
        moogoldVariationId: "5002",
        originalPriceUSD: 5.20,
        sellingPriceUSD: 4.80,
        sellingPriceKHR: 19700,
        isAvailable: true,
        sortOrder: 2,
      },
      {
        id: "pkg-genshin-1090",
        gameId: "game-genshin",
        name: "980 + 110 Genesis Crystals",
        diamondsCount: 980,
        bonusDiamonds: 110,
        moogoldProductId: "14",
        moogoldVariationId: "5003",
        originalPriceUSD: 16.00,
        sellingPriceUSD: 14.50,
        sellingPriceKHR: 59500,
        isAvailable: true,
        badgeText: "💎 VIP Pack",
        sortOrder: 3,
      },
    ],
  },
];
